<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="sawppy">


    <!-- PROPERTIES -->
    <xacro:property name="bottom_plate_height" value="0.003"/>
    <xacro:property name="profile_width" value="0.015"/>

    <xacro:property name="chassis_lenght" value="0.410"/>
    <xacro:property name="chassis_width" value="0.270"/>
    <xacro:property name="corner_height" value="0.080"/> <!-- Remove -->
    <xacro:property name="chassis_height" value="0.080"/>

    <xacro:property name="differential_offset_x" value="-0.015"/>


    <!-- INCLUDES -->
    <xacro:include filename="$(find sawppy_description)/urdf/common_properties.xacro"/>
    <xacro:include filename="$(find sawppy_description)/urdf/body.urdf.xacro"/>
    <xacro:include filename="$(find sawppy_description)/urdf/rocker_bogie.urdf.xacro"/>

    <!-- BODY CHASSIS -->
    <xacro:body/>

    <!-- ROCKER-BOGIE - RIGHT -->
    <xacro:rocker_bogie suffix="right" parent="base_link" reflect="1"/>
        <!--
        <origin xyz="0.0 ${suspension_mount_width/2 + 0.001} 0.0" rpy="0.0 0.0 0.0"/>
        -->
        <!--
        <origin xyz="${suspension_mount_offset_x} -${chassis_width/2} ${bottom_plate_height + suspension_mount_lower_dist + profile_width/2}" rpy="0.0 0.0 0.0"/>
    </xacro:rocker_bogie>
        -->

    <!-- ROCKER-BOGIE - LEFT -->
    <xacro:rocker_bogie suffix="left" parent="base_link" reflect="-1"/>
    <!--
    <xacro:rocker_bogie suffix="left" parent="base_link" reflect="-1">
        <origin xyz="${suspension_mount_offset_x} ${chassis_width/2} ${bottom_plate_height + suspension_mount_lower_dist + profile_width/2}" rpy="0.0 0.0 0.0"/>
    </xacro:rocker_bogie>
    -->


</robot>
