<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki.xacro">

    <xacro:macro name="differential_mount" params="parent offset_x">

        <!-- Right differential mount -->
        <joint name="${parent}_to_differential_mount_r" type="fixed">
            <parent link="${parent}"/>
            <child link="differential_mount_r"/>
            <origin xyz="${offset_x} -${chassis_width/2} ${bottom_plate_height + chassis_height + profile_width/2}" rpy="0.0 0.0 0.0"/>
        </joint>

        <link name="differential_mount_r">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://sawppy_description/meshes/stl/differential_mount_right.stl" scale="${SCALE}"/>
                </geometry>
                <material name="plastic"/>
            </visual>
        </link>

        <!-- Left differential mount-->
        <joint name="${parent}_to_differential_mount_l" type="fixed">
            <parent link="${parent}"/>
            <child link="differential_mount_l"/>
            <origin xyz="${offset_x} ${chassis_width/2} ${bottom_plate_height + chassis_height + profile_width/2}" rpy="0.0 0.0 0.0"/>
        </joint>

        <link name="differential_mount_l">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://sawppy_description/meshes/stl/differential_mount_left.stl" scale="${SCALE}"/>
                </geometry>
                <material name="plastic"/>
            </visual>
        </link>

    </xacro:macro>

</robot>
