<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="profile" params="suffix parent length *origin">

        <joint name="${parent}_to_profile_${suffix}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="profile_${suffix}"/>
            <xacro:insert_block name="origin"/>
        </joint>

        <link name="profile_${suffix}">
            <visual>
                <origin xyz="${length/2000} 0.0 0.0" rpy="${PI/2} 0.0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://sawppy_description/meshes/stl/profile_${length}.stl" scale="${SCALE}"/>
                </geometry>
                <material name="aluminium"/>
            </visual>
        </link>

    </xacro:macro>

</robot>
